// tslint:disable
/**
 * Wallet API
 * Wallet API 명세
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface AggregatedBillingDto
 */
export interface AggregatedBillingDto {
    /**
     * 
     * @type {Array<BillingPerPlanDto>}
     * @memberof AggregatedBillingDto
     */
    billings: Array<BillingPerPlanDto>;
}
/**
 * 
 * @export
 * @interface BasePlanDto
 */
export interface BasePlanDto {
    /**
     * 
     * @type {string}
     * @memberof BasePlanDto
     */
    termFrom: string;
    /**
     * 
     * @type {string}
     * @memberof BasePlanDto
     */
    termUntil: string;
    /**
     * 
     * @type {number}
     * @memberof BasePlanDto
     */
    unitPeriod: number;
    /**
     * 
     * @type {number}
     * @memberof BasePlanDto
     */
    blockchainNetworkFeePerPeriod?: number;
    /**
     * 
     * @type {number}
     * @memberof BasePlanDto
     */
    nftUsageFeePerPeriod?: number;
    /**
     * 
     * @type {number}
     * @memberof BasePlanDto
     */
    fungibleTokenFeePerMonth?: number;
    /**
     * 
     * @type {number}
     * @memberof BasePlanDto
     */
    freeFungibleTokenCount?: number;
    /**
     * 
     * @type {number}
     * @memberof BasePlanDto
     */
    nonFungibleTokenFeePerMonth?: number;
    /**
     * 
     * @type {number}
     * @memberof BasePlanDto
     */
    freeNonFungibleTokenCount?: number;
    /**
     * 
     * @type {number}
     * @memberof BasePlanDto
     */
    withdrawalFeeRate?: number;
    /**
     * 
     * @type {number}
     * @memberof BasePlanDto
     */
    gasSavingFeeRate?: number;
}
/**
 * 
 * @export
 * @interface BillingDto
 */
export interface BillingDto {
    /**
     * 
     * @type {string}
     * @memberof BillingDto
     */
    plan: string;
    /**
     * 
     * @type {string}
     * @memberof BillingDto
     */
    blockchain: string;
    /**
     * 
     * @type {number}
     * @memberof BillingDto
     */
    usageFee: number;
    /**
     * 
     * @type {Array<MonthlyBillingDto>}
     * @memberof BillingDto
     */
    monthlyBillings?: Array<MonthlyBillingDto>;
}
/**
 * 
 * @export
 * @interface BillingPerPlanDto
 */
export interface BillingPerPlanDto {
    /**
     * 
     * @type {string}
     * @memberof BillingPerPlanDto
     */
    plan: string;
    /**
     * 
     * @type {Array<BillingDto>}
     * @memberof BillingPerPlanDto
     */
    billings: Array<BillingDto>;
    /**
     * 
     * @type {number}
     * @memberof BillingPerPlanDto
     */
    totalUsageFee: number;
}
/**
 * 
 * @export
 * @interface CreateErc20GasUsageRequest
 */
export interface CreateErc20GasUsageRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateErc20GasUsageRequest
     */
    blockchain: string;
    /**
     * 
     * @type {string}
     * @memberof CreateErc20GasUsageRequest
     */
    transfer: string;
    /**
     * 
     * @type {string}
     * @memberof CreateErc20GasUsageRequest
     */
    approve: string;
    /**
     * 
     * @type {string}
     * @memberof CreateErc20GasUsageRequest
     */
    transferFrom: string;
}
/**
 * 
 * @export
 * @interface CreateTermInvoiceResponse
 */
export interface CreateTermInvoiceResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateTermInvoiceResponse
     */
    invoiceId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTermInvoiceResponse
     */
    withdrawalFeeInvoiceId?: string;
}
/**
 * 
 * @export
 * @interface DailyBillingDto
 */
export interface DailyBillingDto {
    /**
     * 
     * @type {string}
     * @memberof DailyBillingDto
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof DailyBillingDto
     */
    dailyUsageFee: number;
}
/**
 * 
 * @export
 * @interface DetailedInvoiceDto
 */
export interface DetailedInvoiceDto {
    /**
     * 
     * @type {string}
     * @memberof DetailedInvoiceDto
     */
    invoiceId: string;
    /**
     * 
     * @type {Array<UsageFeeMonthlyBillingDto>}
     * @memberof DetailedInvoiceDto
     */
    monthlyBlockchainNetworkFeeBillings?: Array<UsageFeeMonthlyBillingDto>;
    /**
     * 
     * @type {Array<UsageFeeMonthlyBillingDto>}
     * @memberof DetailedInvoiceDto
     */
    monthlyNftUsageFeeBillings?: Array<UsageFeeMonthlyBillingDto>;
    /**
     * 
     * @type {Array<TokenFeeMonthlyBillingDto>}
     * @memberof DetailedInvoiceDto
     */
    monthlyFungibleTokenFeeBillings?: Array<TokenFeeMonthlyBillingDto>;
    /**
     * 
     * @type {Array<TokenFeeMonthlyBillingDto>}
     * @memberof DetailedInvoiceDto
     */
    monthlyNonFungibleTokenFeeBillings?: Array<TokenFeeMonthlyBillingDto>;
    /**
     * 
     * @type {Array<WithdrawalFeeMonthlyBillingDto>}
     * @memberof DetailedInvoiceDto
     */
    monthlyWithdrawalFeeBillings?: Array<WithdrawalFeeMonthlyBillingDto>;
    /**
     * 
     * @type {Array<GasSavingFeeMonthlyBillingDto>}
     * @memberof DetailedInvoiceDto
     */
    monthlyGasSavingFeeDailyBillings?: Array<GasSavingFeeMonthlyBillingDto>;
}
/**
 * 
 * @export
 * @interface ErrorBody
 */
export interface ErrorBody {
    /**
     * 
     * @type {string}
     * @memberof ErrorBody
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorBody
     */
    code?: number;
}
/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {ErrorBody}
     * @memberof ErrorResponse
     */
    error?: ErrorBody;
}
/**
 * 
 * @export
 * @interface GasSavingFeeDailyBillingDto
 */
export interface GasSavingFeeDailyBillingDto {
    /**
     * 
     * @type {string}
     * @memberof GasSavingFeeDailyBillingDto
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof GasSavingFeeDailyBillingDto
     */
    henesisGasAmount: number;
    /**
     * 
     * @type {number}
     * @memberof GasSavingFeeDailyBillingDto
     */
    customerGasAmount: number;
    /**
     * 
     * @type {number}
     * @memberof GasSavingFeeDailyBillingDto
     */
    savedGasAmount: number;
    /**
     * 
     * @type {number}
     * @memberof GasSavingFeeDailyBillingDto
     */
    closePrice: number;
    /**
     * 
     * @type {number}
     * @memberof GasSavingFeeDailyBillingDto
     */
    gasSavingFee: number;
}
/**
 * 
 * @export
 * @interface GasSavingFeeMonthlyBillingDto
 */
export interface GasSavingFeeMonthlyBillingDto {
    /**
     * 
     * @type {string}
     * @memberof GasSavingFeeMonthlyBillingDto
     */
    billingMonth: string;
    /**
     * 
     * @type {Array<GasSavingFeeDailyBillingDto>}
     * @memberof GasSavingFeeMonthlyBillingDto
     */
    gasSavingFeeDailyBillings: Array<GasSavingFeeDailyBillingDto>;
}
/**
 * 
 * @export
 * @interface MonthlyBillingDto
 */
export interface MonthlyBillingDto {
    /**
     * 
     * @type {string}
     * @memberof MonthlyBillingDto
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof MonthlyBillingDto
     */
    until: string;
    /**
     * 
     * @type {number}
     * @memberof MonthlyBillingDto
     */
    totalUsageFee: number;
    /**
     * 
     * @type {Array<DailyBillingDto>}
     * @memberof MonthlyBillingDto
     */
    dailyBillings?: Array<DailyBillingDto>;
}
/**
 * 
 * @export
 * @interface OrganizationDto
 */
export interface OrganizationDto {
    /**
     * 
     * @type {string}
     * @memberof OrganizationDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDto
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDto
     */
    language: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDto
     */
    orgId: string;
    /**
     * 
     * @type {BasePlanDto}
     * @memberof OrganizationDto
     */
    basePlan: BasePlanDto;
}
/**
 * 
 * @export
 * @interface PatchErc20GasUsageRequest
 */
export interface PatchErc20GasUsageRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchErc20GasUsageRequest
     */
    blockchain: string;
    /**
     * 
     * @type {string}
     * @memberof PatchErc20GasUsageRequest
     */
    transfer: string;
    /**
     * 
     * @type {string}
     * @memberof PatchErc20GasUsageRequest
     */
    approve: string;
    /**
     * 
     * @type {string}
     * @memberof PatchErc20GasUsageRequest
     */
    transferFrom: string;
}
/**
 * 
 * @export
 * @interface SaveBillingOrganizationRequest
 */
export interface SaveBillingOrganizationRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveBillingOrganizationRequest
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof SaveBillingOrganizationRequest
     */
    language: string;
    /**
     * 
     * @type {string}
     * @memberof SaveBillingOrganizationRequest
     */
    coinSource: string;
    /**
     * 
     * @type {string}
     * @memberof SaveBillingOrganizationRequest
     */
    contractType: string;
    /**
     * 
     * @type {BasePlanDto}
     * @memberof SaveBillingOrganizationRequest
     */
    basePlan: BasePlanDto;
}
/**
 * 
 * @export
 * @interface SummarizedBlockchainNetworkFeeBillingDto
 */
export interface SummarizedBlockchainNetworkFeeBillingDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof SummarizedBlockchainNetworkFeeBillingDto
     */
    blockchains: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SummarizedBlockchainNetworkFeeBillingDto
     */
    totalBlockchainNetworkFee: number;
}
/**
 * 
 * @export
 * @interface SummarizedGasSavingFeeBillingDto
 */
export interface SummarizedGasSavingFeeBillingDto {
    /**
     * 
     * @type {string}
     * @memberof SummarizedGasSavingFeeBillingDto
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof SummarizedGasSavingFeeBillingDto
     */
    until: string;
    /**
     * 
     * @type {number}
     * @memberof SummarizedGasSavingFeeBillingDto
     */
    totalGasSavingAmount: number;
    /**
     * 
     * @type {number}
     * @memberof SummarizedGasSavingFeeBillingDto
     */
    gasSavingFee: number;
    /**
     * 
     * @type {number}
     * @memberof SummarizedGasSavingFeeBillingDto
     */
    gasSavingFeeRate: number;
}
/**
 * 
 * @export
 * @interface SummarizedInvoiceDto
 */
export interface SummarizedInvoiceDto {
    /**
     * 
     * @type {string}
     * @memberof SummarizedInvoiceDto
     */
    invoiceId: string;
    /**
     * 
     * @type {string}
     * @memberof SummarizedInvoiceDto
     */
    invoiceType: string;
    /**
     * 
     * @type {string}
     * @memberof SummarizedInvoiceDto
     */
    usageFrom: string;
    /**
     * 
     * @type {string}
     * @memberof SummarizedInvoiceDto
     */
    usageUntil: string;
    /**
     * 
     * @type {number}
     * @memberof SummarizedInvoiceDto
     */
    supplyValue: number;
    /**
     * 
     * @type {number}
     * @memberof SummarizedInvoiceDto
     */
    totalValue: number;
    /**
     * 
     * @type {string}
     * @memberof SummarizedInvoiceDto
     */
    billingMonth: string;
    /**
     * 
     * @type {string}
     * @memberof SummarizedInvoiceDto
     */
    billingDate: string;
    /**
     * 
     * @type {string}
     * @memberof SummarizedInvoiceDto
     */
    paymentDueDate: string;
    /**
     * 
     * @type {SummarizedOrganizationDto}
     * @memberof SummarizedInvoiceDto
     */
    summarizedOrganization?: SummarizedOrganizationDto;
    /**
     * 
     * @type {SummarizedBlockchainNetworkFeeBillingDto}
     * @memberof SummarizedInvoiceDto
     */
    summarizedBlockchainNetworkFeeBilling?: SummarizedBlockchainNetworkFeeBillingDto;
    /**
     * 
     * @type {SummarizedNftUsageFeeBillingDto}
     * @memberof SummarizedInvoiceDto
     */
    summarizedNftUsageFeeBilling?: SummarizedNftUsageFeeBillingDto;
    /**
     * 
     * @type {SummarizedTokenFeeBillingDto}
     * @memberof SummarizedInvoiceDto
     */
    summarizedTokenFeeBilling?: SummarizedTokenFeeBillingDto;
    /**
     * 
     * @type {SummarizedWithdrawalFeeBillingDto}
     * @memberof SummarizedInvoiceDto
     */
    summarizedWithdrawalFeeBilling?: SummarizedWithdrawalFeeBillingDto;
    /**
     * 
     * @type {SummarizedGasSavingFeeBillingDto}
     * @memberof SummarizedInvoiceDto
     */
    summarizedGasSavingFeeBilling?: SummarizedGasSavingFeeBillingDto;
}
/**
 * 
 * @export
 * @interface SummarizedNftUsageFeeBillingDto
 */
export interface SummarizedNftUsageFeeBillingDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof SummarizedNftUsageFeeBillingDto
     */
    blockchains: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SummarizedNftUsageFeeBillingDto
     */
    totalNftUsageFee: number;
}
/**
 * 
 * @export
 * @interface SummarizedOrganizationDto
 */
export interface SummarizedOrganizationDto {
    /**
     * 
     * @type {string}
     * @memberof SummarizedOrganizationDto
     */
    orgName: string;
    /**
     * 
     * @type {string}
     * @memberof SummarizedOrganizationDto
     */
    contractType: string;
    /**
     * 
     * @type {string}
     * @memberof SummarizedOrganizationDto
     */
    termFrom: string;
    /**
     * 
     * @type {string}
     * @memberof SummarizedOrganizationDto
     */
    termUntil: string;
    /**
     * 
     * @type {number}
     * @memberof SummarizedOrganizationDto
     */
    unitPeriod: number;
    /**
     * 
     * @type {number}
     * @memberof SummarizedOrganizationDto
     */
    blockchainNetworkFeePerPeriod: number;
    /**
     * 
     * @type {number}
     * @memberof SummarizedOrganizationDto
     */
    nftUsageFeePerPeriod: number;
    /**
     * 
     * @type {number}
     * @memberof SummarizedOrganizationDto
     */
    fungibleTokenFeePerMonth: number;
    /**
     * 
     * @type {number}
     * @memberof SummarizedOrganizationDto
     */
    freeFungibleTokenCount: number;
    /**
     * 
     * @type {number}
     * @memberof SummarizedOrganizationDto
     */
    nonFungibleTokenFeePerMonth: number;
    /**
     * 
     * @type {number}
     * @memberof SummarizedOrganizationDto
     */
    freeNonFungibleTokenCount: number;
    /**
     * 
     * @type {number}
     * @memberof SummarizedOrganizationDto
     */
    withdrawalFeeRate: number;
    /**
     * 
     * @type {number}
     * @memberof SummarizedOrganizationDto
     */
    gasSavingFeeRate: number;
}
/**
 * 
 * @export
 * @interface SummarizedTokenFeeBillingDto
 */
export interface SummarizedTokenFeeBillingDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof SummarizedTokenFeeBillingDto
     */
    tokens: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SummarizedTokenFeeBillingDto
     */
    totalTokenFee: number;
}
/**
 * 
 * @export
 * @interface SummarizedWithdrawalFeeBillingDto
 */
export interface SummarizedWithdrawalFeeBillingDto {
    /**
     * 
     * @type {string}
     * @memberof SummarizedWithdrawalFeeBillingDto
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof SummarizedWithdrawalFeeBillingDto
     */
    until: string;
    /**
     * 
     * @type {number}
     * @memberof SummarizedWithdrawalFeeBillingDto
     */
    totalWithdrawalAmount: number;
    /**
     * 
     * @type {number}
     * @memberof SummarizedWithdrawalFeeBillingDto
     */
    withdrawalFee: number;
    /**
     * 
     * @type {number}
     * @memberof SummarizedWithdrawalFeeBillingDto
     */
    withdrawalFeeRate: number;
}
/**
 * 
 * @export
 * @interface TokenFeeMonthlyBillingDto
 */
export interface TokenFeeMonthlyBillingDto {
    /**
     * 
     * @type {string}
     * @memberof TokenFeeMonthlyBillingDto
     */
    blockchain: string;
    /**
     * 
     * @type {boolean}
     * @memberof TokenFeeMonthlyBillingDto
     */
    free?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TokenFeeMonthlyBillingDto
     */
    billingMonth: string;
    /**
     * 
     * @type {number}
     * @memberof TokenFeeMonthlyBillingDto
     */
    coinId: number;
    /**
     * 
     * @type {string}
     * @memberof TokenFeeMonthlyBillingDto
     */
    tokenType: string;
    /**
     * 
     * @type {string}
     * @memberof TokenFeeMonthlyBillingDto
     */
    tokenName: string;
    /**
     * 
     * @type {string}
     * @memberof TokenFeeMonthlyBillingDto
     */
    tokenSymbol: string;
    /**
     * 
     * @type {boolean}
     * @memberof TokenFeeMonthlyBillingDto
     */
    isFree: boolean;
    /**
     * 
     * @type {string}
     * @memberof TokenFeeMonthlyBillingDto
     */
    usageFrom: string;
    /**
     * 
     * @type {string}
     * @memberof TokenFeeMonthlyBillingDto
     */
    usageUntil: string;
    /**
     * 
     * @type {number}
     * @memberof TokenFeeMonthlyBillingDto
     */
    usageFee: number;
}
/**
 * 
 * @export
 * @interface UsageFeeMonthlyBillingDto
 */
export interface UsageFeeMonthlyBillingDto {
    /**
     * 
     * @type {string}
     * @memberof UsageFeeMonthlyBillingDto
     */
    blockchain: string;
    /**
     * 
     * @type {string}
     * @memberof UsageFeeMonthlyBillingDto
     */
    billingMonth: string;
    /**
     * 
     * @type {string}
     * @memberof UsageFeeMonthlyBillingDto
     */
    usageFrom: string;
    /**
     * 
     * @type {string}
     * @memberof UsageFeeMonthlyBillingDto
     */
    usageUntil: string;
    /**
     * 
     * @type {number}
     * @memberof UsageFeeMonthlyBillingDto
     */
    usageFee: number;
    /**
     * 
     * @type {number}
     * @memberof UsageFeeMonthlyBillingDto
     */
    discountRate: number;
}
/**
 * 
 * @export
 * @interface WithdrawalFeeDailyBillingDto
 */
export interface WithdrawalFeeDailyBillingDto {
    /**
     * 
     * @type {string}
     * @memberof WithdrawalFeeDailyBillingDto
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof WithdrawalFeeDailyBillingDto
     */
    blockchain: string;
    /**
     * 
     * @type {string}
     * @memberof WithdrawalFeeDailyBillingDto
     */
    coinSymbol: string;
    /**
     * 
     * @type {number}
     * @memberof WithdrawalFeeDailyBillingDto
     */
    closePrice: number;
    /**
     * 
     * @type {number}
     * @memberof WithdrawalFeeDailyBillingDto
     */
    withdrawalAmount: number;
    /**
     * 
     * @type {number}
     * @memberof WithdrawalFeeDailyBillingDto
     */
    withdrawalFee: number;
}
/**
 * 
 * @export
 * @interface WithdrawalFeeMonthlyBillingDto
 */
export interface WithdrawalFeeMonthlyBillingDto {
    /**
     * 
     * @type {string}
     * @memberof WithdrawalFeeMonthlyBillingDto
     */
    blockchain: string;
    /**
     * 
     * @type {string}
     * @memberof WithdrawalFeeMonthlyBillingDto
     */
    coinSource: string;
    /**
     * 
     * @type {string}
     * @memberof WithdrawalFeeMonthlyBillingDto
     */
    billingMonth: string;
    /**
     * 
     * @type {Array<WithdrawalFeeDailyBillingDto>}
     * @memberof WithdrawalFeeMonthlyBillingDto
     */
    withdrawalFeeDailyBillings: Array<WithdrawalFeeDailyBillingDto>;
}

/**
 * BillingControllerApi - axios parameter creator
 * @export
 */
export const BillingControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} orgId 
         * @param {string} searchStartDate 
         * @param {string} [searchEndDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBillings: async (orgId: string, searchStartDate: string, searchEndDate?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling getBillings.');
            }
            // verify required parameter 'searchStartDate' is not null or undefined
            if (searchStartDate === null || searchStartDate === undefined) {
                throw new RequiredError('searchStartDate','Required parameter searchStartDate was null or undefined when calling getBillings.');
            }
            const localVarPath = `/api/v1/billings`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (orgId !== undefined) {
                localVarQueryParameter['org_id'] = orgId;
            }

            if (searchStartDate !== undefined) {
                localVarQueryParameter['search_start_date'] = (searchStartDate as any instanceof Date) ?
                    (searchStartDate as any).toISOString().substr(0,10) :
                    searchStartDate;
            }

            if (searchEndDate !== undefined) {
                localVarQueryParameter['search_end_date'] = (searchEndDate as any instanceof Date) ?
                    (searchEndDate as any).toISOString().substr(0,10) :
                    searchEndDate;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BillingControllerApi - functional programming interface
 * @export
 */
export const BillingControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} orgId 
         * @param {string} searchStartDate 
         * @param {string} [searchEndDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBillings(orgId: string, searchStartDate: string, searchEndDate?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AggregatedBillingDto>> {
            const localVarAxiosArgs = await BillingControllerApiAxiosParamCreator(configuration).getBillings(orgId, searchStartDate, searchEndDate, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * BillingControllerApi - factory interface
 * @export
 */
export const BillingControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} orgId 
         * @param {string} searchStartDate 
         * @param {string} [searchEndDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBillings(orgId: string, searchStartDate: string, searchEndDate?: string, options?: any): AxiosPromise<AggregatedBillingDto> {
            return BillingControllerApiFp(configuration).getBillings(orgId, searchStartDate, searchEndDate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BillingControllerApi - object-oriented interface
 * @export
 * @class BillingControllerApi
 * @extends {BaseAPI}
 */
export class BillingControllerApi extends BaseAPI {
    /**
     * 
     * @param {string} orgId 
     * @param {string} searchStartDate 
     * @param {string} [searchEndDate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingControllerApi
     */
    public getBillings(orgId: string, searchStartDate: string, searchEndDate?: string, options?: any) {
        return BillingControllerApiFp(this.configuration).getBillings(orgId, searchStartDate, searchEndDate, options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * InvoiceControllerApi - axios parameter creator
 * @export
 */
export const InvoiceControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} orgId 
         * @param {string} date 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTermInvoice: async (orgId: string, date: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling createTermInvoice.');
            }
            // verify required parameter 'date' is not null or undefined
            if (date === null || date === undefined) {
                throw new RequiredError('date','Required parameter date was null or undefined when calling createTermInvoice.');
            }
            const localVarPath = `/api/v1/invoices/organizations/{orgId}/create-term-invoice`
                .replace(`{${"orgId"}}`, encodeURIComponent(String(orgId)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (date !== undefined) {
                localVarQueryParameter['date'] = date;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} invoiceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDetailedInvoice: async (invoiceId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'invoiceId' is not null or undefined
            if (invoiceId === null || invoiceId === undefined) {
                throw new RequiredError('invoiceId','Required parameter invoiceId was null or undefined when calling getDetailedInvoice.');
            }
            const localVarPath = `/api/v1/invoices/{invoiceId}/detailed`
                .replace(`{${"invoiceId"}}`, encodeURIComponent(String(invoiceId)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} invoiceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSummarizedInvoice: async (invoiceId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'invoiceId' is not null or undefined
            if (invoiceId === null || invoiceId === undefined) {
                throw new RequiredError('invoiceId','Required parameter invoiceId was null or undefined when calling getSummarizedInvoice.');
            }
            const localVarPath = `/api/v1/invoices/{invoiceId}/summarized`
                .replace(`{${"invoiceId"}}`, encodeURIComponent(String(invoiceId)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InvoiceControllerApi - functional programming interface
 * @export
 */
export const InvoiceControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} orgId 
         * @param {string} date 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTermInvoice(orgId: string, date: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateTermInvoiceResponse>> {
            const localVarAxiosArgs = await InvoiceControllerApiAxiosParamCreator(configuration).createTermInvoice(orgId, date, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} invoiceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDetailedInvoice(invoiceId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DetailedInvoiceDto>> {
            const localVarAxiosArgs = await InvoiceControllerApiAxiosParamCreator(configuration).getDetailedInvoice(invoiceId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} invoiceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSummarizedInvoice(invoiceId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SummarizedInvoiceDto>> {
            const localVarAxiosArgs = await InvoiceControllerApiAxiosParamCreator(configuration).getSummarizedInvoice(invoiceId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * InvoiceControllerApi - factory interface
 * @export
 */
export const InvoiceControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} orgId 
         * @param {string} date 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTermInvoice(orgId: string, date: string, options?: any): AxiosPromise<CreateTermInvoiceResponse> {
            return InvoiceControllerApiFp(configuration).createTermInvoice(orgId, date, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} invoiceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDetailedInvoice(invoiceId: string, options?: any): AxiosPromise<DetailedInvoiceDto> {
            return InvoiceControllerApiFp(configuration).getDetailedInvoice(invoiceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} invoiceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSummarizedInvoice(invoiceId: string, options?: any): AxiosPromise<SummarizedInvoiceDto> {
            return InvoiceControllerApiFp(configuration).getSummarizedInvoice(invoiceId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InvoiceControllerApi - object-oriented interface
 * @export
 * @class InvoiceControllerApi
 * @extends {BaseAPI}
 */
export class InvoiceControllerApi extends BaseAPI {
    /**
     * 
     * @param {string} orgId 
     * @param {string} date 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoiceControllerApi
     */
    public createTermInvoice(orgId: string, date: string, options?: any) {
        return InvoiceControllerApiFp(this.configuration).createTermInvoice(orgId, date, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} invoiceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoiceControllerApi
     */
    public getDetailedInvoice(invoiceId: string, options?: any) {
        return InvoiceControllerApiFp(this.configuration).getDetailedInvoice(invoiceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} invoiceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoiceControllerApi
     */
    public getSummarizedInvoice(invoiceId: string, options?: any) {
        return InvoiceControllerApiFp(this.configuration).getSummarizedInvoice(invoiceId, options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * OrganizationControllerApi - axios parameter creator
 * @export
 */
export const OrganizationControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} orgId 
         * @param {SaveBillingOrganizationRequest} saveBillingOrganizationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveBillingOrganization: async (orgId: string, saveBillingOrganizationRequest: SaveBillingOrganizationRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling saveBillingOrganization.');
            }
            // verify required parameter 'saveBillingOrganizationRequest' is not null or undefined
            if (saveBillingOrganizationRequest === null || saveBillingOrganizationRequest === undefined) {
                throw new RequiredError('saveBillingOrganizationRequest','Required parameter saveBillingOrganizationRequest was null or undefined when calling saveBillingOrganization.');
            }
            const localVarPath = `/api/v1/organizations/{orgId}`
                .replace(`{${"orgId"}}`, encodeURIComponent(String(orgId)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof saveBillingOrganizationRequest !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(saveBillingOrganizationRequest !== undefined ? saveBillingOrganizationRequest : {}) : (saveBillingOrganizationRequest || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrganizationControllerApi - functional programming interface
 * @export
 */
export const OrganizationControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} orgId 
         * @param {SaveBillingOrganizationRequest} saveBillingOrganizationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveBillingOrganization(orgId: string, saveBillingOrganizationRequest: SaveBillingOrganizationRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationDto>> {
            const localVarAxiosArgs = await OrganizationControllerApiAxiosParamCreator(configuration).saveBillingOrganization(orgId, saveBillingOrganizationRequest, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * OrganizationControllerApi - factory interface
 * @export
 */
export const OrganizationControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} orgId 
         * @param {SaveBillingOrganizationRequest} saveBillingOrganizationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveBillingOrganization(orgId: string, saveBillingOrganizationRequest: SaveBillingOrganizationRequest, options?: any): AxiosPromise<OrganizationDto> {
            return OrganizationControllerApiFp(configuration).saveBillingOrganization(orgId, saveBillingOrganizationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OrganizationControllerApi - object-oriented interface
 * @export
 * @class OrganizationControllerApi
 * @extends {BaseAPI}
 */
export class OrganizationControllerApi extends BaseAPI {
    /**
     * 
     * @param {string} orgId 
     * @param {SaveBillingOrganizationRequest} saveBillingOrganizationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganizationControllerApi
     */
    public saveBillingOrganization(orgId: string, saveBillingOrganizationRequest: SaveBillingOrganizationRequest, options?: any) {
        return OrganizationControllerApiFp(this.configuration).saveBillingOrganization(orgId, saveBillingOrganizationRequest, options).then((request) => request(this.axios, this.basePath));
    }

}


/**
 * SupportControllerApi - axios parameter creator
 * @export
 */
export const SupportControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} coinId 
         * @param {CreateErc20GasUsageRequest} createErc20GasUsageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createErc20GasUsage: async (coinId: number, createErc20GasUsageRequest: CreateErc20GasUsageRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'coinId' is not null or undefined
            if (coinId === null || coinId === undefined) {
                throw new RequiredError('coinId','Required parameter coinId was null or undefined when calling createErc20GasUsage.');
            }
            // verify required parameter 'createErc20GasUsageRequest' is not null or undefined
            if (createErc20GasUsageRequest === null || createErc20GasUsageRequest === undefined) {
                throw new RequiredError('createErc20GasUsageRequest','Required parameter createErc20GasUsageRequest was null or undefined when calling createErc20GasUsage.');
            }
            const localVarPath = `/api/v1/supports/erc20-gas-usage/{coinId}`
                .replace(`{${"coinId"}}`, encodeURIComponent(String(coinId)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof createErc20GasUsageRequest !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(createErc20GasUsageRequest !== undefined ? createErc20GasUsageRequest : {}) : (createErc20GasUsageRequest || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} coinId 
         * @param {PatchErc20GasUsageRequest} patchErc20GasUsageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchErc20GasUsage: async (coinId: number, patchErc20GasUsageRequest: PatchErc20GasUsageRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'coinId' is not null or undefined
            if (coinId === null || coinId === undefined) {
                throw new RequiredError('coinId','Required parameter coinId was null or undefined when calling patchErc20GasUsage.');
            }
            // verify required parameter 'patchErc20GasUsageRequest' is not null or undefined
            if (patchErc20GasUsageRequest === null || patchErc20GasUsageRequest === undefined) {
                throw new RequiredError('patchErc20GasUsageRequest','Required parameter patchErc20GasUsageRequest was null or undefined when calling patchErc20GasUsage.');
            }
            const localVarPath = `/api/v1/supports/erc20-gas-usage/{coinId}`
                .replace(`{${"coinId"}}`, encodeURIComponent(String(coinId)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof patchErc20GasUsageRequest !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(patchErc20GasUsageRequest !== undefined ? patchErc20GasUsageRequest : {}) : (patchErc20GasUsageRequest || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SupportControllerApi - functional programming interface
 * @export
 */
export const SupportControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} coinId 
         * @param {CreateErc20GasUsageRequest} createErc20GasUsageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createErc20GasUsage(coinId: number, createErc20GasUsageRequest: CreateErc20GasUsageRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await SupportControllerApiAxiosParamCreator(configuration).createErc20GasUsage(coinId, createErc20GasUsageRequest, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {number} coinId 
         * @param {PatchErc20GasUsageRequest} patchErc20GasUsageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchErc20GasUsage(coinId: number, patchErc20GasUsageRequest: PatchErc20GasUsageRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await SupportControllerApiAxiosParamCreator(configuration).patchErc20GasUsage(coinId, patchErc20GasUsageRequest, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SupportControllerApi - factory interface
 * @export
 */
export const SupportControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {number} coinId 
         * @param {CreateErc20GasUsageRequest} createErc20GasUsageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createErc20GasUsage(coinId: number, createErc20GasUsageRequest: CreateErc20GasUsageRequest, options?: any): AxiosPromise<void> {
            return SupportControllerApiFp(configuration).createErc20GasUsage(coinId, createErc20GasUsageRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} coinId 
         * @param {PatchErc20GasUsageRequest} patchErc20GasUsageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchErc20GasUsage(coinId: number, patchErc20GasUsageRequest: PatchErc20GasUsageRequest, options?: any): AxiosPromise<void> {
            return SupportControllerApiFp(configuration).patchErc20GasUsage(coinId, patchErc20GasUsageRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SupportControllerApi - object-oriented interface
 * @export
 * @class SupportControllerApi
 * @extends {BaseAPI}
 */
export class SupportControllerApi extends BaseAPI {
    /**
     * 
     * @param {number} coinId 
     * @param {CreateErc20GasUsageRequest} createErc20GasUsageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SupportControllerApi
     */
    public createErc20GasUsage(coinId: number, createErc20GasUsageRequest: CreateErc20GasUsageRequest, options?: any) {
        return SupportControllerApiFp(this.configuration).createErc20GasUsage(coinId, createErc20GasUsageRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} coinId 
     * @param {PatchErc20GasUsageRequest} patchErc20GasUsageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SupportControllerApi
     */
    public patchErc20GasUsage(coinId: number, patchErc20GasUsageRequest: PatchErc20GasUsageRequest, options?: any) {
        return SupportControllerApiFp(this.configuration).patchErc20GasUsage(coinId, patchErc20GasUsageRequest, options).then((request) => request(this.axios, this.basePath));
    }

}


