language: node_js

node_js:
  - "10.15"

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

cache:
  npm: true

branches:
  only:
    - master

before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:
  - provider: script
    skip-cleanup: true
    script: scripts/deploy.sh prod
    on:
      tags: true

before_install:
  - sudo apt install -y build-essential

addons:
  apt:
    update: true

install:
  - npm run codegen
  - npm run bootstrap

script:
  - bash ./scripts/core.sh
  - bash ./scripts/enclave.sh
