openapi: 3.0.0
info:
  title: VERSION
  description: Henesis API Proxy  - version OpenAPI Documentation
  version: '1.0'
  contact: {}
tags: []
servers:
  - url: http://localhost:3000
components: {}
paths:
  /api/version:
    get:
      operationId: version-VersionController_getVersion
      x-readme:
        explorer-enabled: false
        samples-languages:
          - curl
          - node
          - java
          - python
          - go
      summary: API Proxy 버전
      description: 현재 API Proxy의 버전을 반환합니다
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - version
