export function random(bytes: any): string;
export function length(a: any): number;
export function concat(a: any, b: any): any;
export function flatten(a: any): string;
export function slice(i: any, j: any, bs: any): string;
export function reverse(hex: any): string;
export function pad(l: any, hex: any): any;
export function padRight(l: any, hex: any): any;
export function fromAscii(ascii: any): string;
export function toAscii(hex: any): string;
export function fromString(s: any): string;
export function toString(bytes: any): string;
export function fromNumber(num: any): string;
export function toNumber(hex: any): number;
export function fromNat(bn: any): any;
export function toNat(bn: any): any;
export function fromArray(arr: any): string;
export function toArray(hex: any): number[];
export function fromUint8Array(arr: any): string;
export function toUint8Array(hex: any): Uint8Array;
