name: Github Actions CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.15]
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: olegtarasov/get-tag@v2
        id: tagName

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: deploy
        run: bash ./scripts/deploy.sh prod

      - name: install
        run: |
          sudo apt install -y build-essential
          npm ci
          npm install
          npm run codegen
          npm run bootstrap
        env:
          CI: true

      - name: script
        run: |
          bash ./scripts/core.sh
          bash ./scripts/enclave.sh
